In [3]:
import numpy as np

In [5]:
import pandas as pd

In [10]:
data = {
    'Numeric1':[1, np.nan, 3, 4],
    'Numeric2':[5, 6, np.nan, 8.2],
    'Numeric3':['dog', np.nan, 'cat', 'dog']}

In [11]:
df = pd.DataFrame(data)

In [12]:
df[df['Numeric2']>5]='5보다 크다'

C:\Users\USER\AppData\Local\Temp\ipykernel_9836\490680127.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '5보다 크다' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[df['Numeric2']>5]='5보다 크다'
C:\Users\USER\AppData\Local\Temp\ipykernel_9836\490680127.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '5보다 크다' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[df['Numeric2']>5]='5보다 크다'

In [13]:
df[df['Numeric2']<8]='8보다 작다'

TypeError: '<' not supported between instances of 'str' and 'int'

In [14]:
data = {
    '나이':[22, 35, 14, 55, 42]}

In [15]:
df = pd.DataFrame(data)

In [19]:
def categorize(data):
    if 0 < data <= 10:
        return "10대 이하"
    elif 10 < data <= 20:
        return "10대"
    elif 20 < data <= 30:
        return "20대"
    else:
        return "30대 이상"

In [20]:
df["검사나이"] = df["나이"].apply(categorize)

In [21]:
df

   나이    검사나이
0  22     20대
1  35  20대 이상
2  14     10대
3  55  20대 이상
4  42  20대 이상

In [24]:
data = {
    'Numeric1':[1, np.nan, 3, 4],
    'Numeric2':[5, 6, np.nan, 8.2],
    'Category':['dog', np.nan, 'cat', 'dogg']}

In [25]:
df = pd.DataFrame(data)

In [29]:
filter_df = df[df['Category'] == 'dog']
filter_df

   Numeric1  Numeric2 Category
0       1.0       5.0      dog

In [30]:
filter_df_contains = df[df['Category'].str.contains('do', na=False)]
filter_df_contains

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
3       4.0       8.2     dogg

In [57]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value4-value5', 'value6']})

In [58]:
split_df = df['variable'].str.split('-', expand=True)
split_df

        0       1       2
0  value1  value2  value3
1  value4  value5    None
2  value6    None    None

In [59]:
split_df.columns = ['var1', 'var2', 'var3']
split_df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [60]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value4-value5', 'value6']})

In [61]:
df['variable'] = df['variable'].str[0:5]
df['variable']

0    value
1    value
2    value
Name: variable, dtype: object

In [62]:
df['variable'] = df['variable'].str[0:5] + df['variable'].str[6:12]
df['variable']

0    value
1    value
2    value
Name: variable, dtype: object

In [69]:
df['var1'] = split_df['var1'].astype(str)
df['var2'] = split_df['var2'].astype(str)
df['var3'] = split_df['var3'].astype(str)

In [47]:
text = 'apple,'
result = text.rstrip(',')
print(result)

apple

In [48]:
text = 'banana,,'
result = text.rstrip(',')
print(result)

banana

In [50]:
text = ',orange, pear'
result = text.lstrip(',')
print(result)

orange, pear

In [71]:
df = pd.DataFrame({
    '문항1':['1', '2', "", '2'],
    '문항2':["", '2', '3', ""]})

In [72]:
df['문항'] = df['문항1'].fillna("") + ", " + df['문항2'].fillna("")
df['문항'] = df['문항1'].str.rstrip(", ")
df['문항'] = df['문항1'].str.lstrip(", ")
df = df.drop(columns = ['문항1', '문항2'])
print(df)

  문항
0  1
1  2
2
3  2

In [80]:
df = pd.DataFrame({
    '문항1':['1', '2', "", '2'],
    '문항2':["", '2', '3', ""],
    '문항3':["", '1', '2', ""]})

In [81]:
cols = ['문항1', '문항2', '문항3']
df[cols] = df[cols].replace(r'^\s*$', '무응답', regex=True)

In [76]:
df['문항'] = df['문항1'].fillna("") + ", " + df['문항2'].fillna("") + ", " + df['문항3'].fillna("")

In [77]:
df

   문항1  문항2  문항3           문항
0    1  무응답  무응답  1, 무응답, 무응답
1    2    2    1      2, 2, 1
2  무응답    3    2    무응답, 3, 2
3    2  무응답  무응답  2, 무응답, 무응답

In [82]:
df['문항'] = df['문항1'] + ", " + df['문항2'] + ", " + df['문항3']

In [83]:
df

   문항1  문항2  문항3           문항
0    1  무응답  무응답  1, 무응답, 무응답
1    2    2    1      2, 2, 1
2  무응답    3    2    무응답, 3, 2
3    2  무응답  무응답  2, 무응답, 무응답

In [84]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value3-value1-value5', 'vvdfvalue165656']})

In [85]:
df['new_variable'] = df['variable'].str.replace(r'value1.*', 'value1', regex=True)

In [86]:
df['new_variable']

0           value1
1    value3-value1
2       vvdfvalue1
Name: new_variable, dtype: object

In [90]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value3-value1-value5', 'vvdfvalue165656']})

In [88]:
df['new_variable'] = df['variable'].str.extract(r'(value1)')
df['new_variable']

0    value1
1    value1
2    value1
Name: new_variable, dtype: object

In [91]:
df['new_variable'] = df['variable'].str.extract(r'(value2)')
df['new_variable']

0    value2
1       NaN
2       NaN
Name: new_variable, dtype: object

In [116]:
data = {'date':['202103151345', '20210315 1345', '0715', '07-15', '20210315', '1']}
df = pd.DataFrame(data)

In [108]:
df['date'] = pd.to_datetime(df['date'],format='%Y%m%d %H%M', errors='coerce')
df['date']

0                   NaT
1   2021-03-15 13:45:00
2                   NaT
3                   NaT
4                   NaT
5                   NaT
Name: date, dtype: datetime64[ns]

In [110]:
df['date'] = pd.to_datetime(df['date'],format='%H-%M', errors='coerce').dt.time
df['date']

0         NaT
1         NaT
2         NaT
3    07:15:00
4         NaT
5         NaT
Name: date, dtype: object

In [106]:
df['date'] = df['date'] = pd.to_datetime(df['date'],format='%Y%m%d', errors='coerce')
df['date']

0          NaT
1          NaT
2          NaT
3          NaT
4   2021-03-15
5          NaT
Name: date, dtype: datetime64[ns]

In [135]:
data = {'hour':['1', '2', '12', '22', '11']}
df = pd.DataFrame(data)

In [136]:
pd.to_datetime(df['hour'], format = '%H%M', errors='coerce').dt.time

0         NaT
1         NaT
2    01:02:00
3    02:02:00
4    01:01:00
Name: hour, dtype: object

In [124]:
df['hour'].str.rjust(1, fillchar = '0')
df['hour'] = df['hour'].str.rjust(4, fillchar = '0')
df['hour']

0    0001
1    0002
2    0012
3    0022
4    0011
Name: hour, dtype: object

In [129]:
df['hour'].str.ljust(1, fillchar = '0')
df['hour'] = df['hour'].str.ljust(4, fillchar = '0')
df['hour']

0    1000
1    2000
2    1200
3    2200
4    1100
Name: hour, dtype: object

In [137]:
df.to_csv('new_program.csv', index=False, encoding='cp949')

In [139]:
df = pd.read_csv('program_1.csv', header=0, encoding='cp949')

In [153]:
df

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균 평가분류
0  A     57   24.0   85.0   47.0  53.25    하
1  B     56   98.0   65.0    0.0  54.75    하
2  C     62   89.0   72.4   66.0  72.35    상
3  D     54   63.2   94.0   54.0  66.30    중
4  E     54   54.0   47.0   84.0  59.75    중
5  F     23   51.0   71.0   50.2  48.80    하

In [146]:
df['프로그램2'] = df['프로그램2'].fillna(df['프로그램2'].mean())

In [144]:
df['프로그램3'] = df['프로그램3'].fillna(df['프로그램3'].mean())

In [147]:
df['프로그램4'] = df['프로그램4'].fillna(df['프로그램4'].mean())

In [149]:
df['평균'] = (df['프로그램1'] + df['프로그램2'] + df['프로그램3'] + df['프로그램4']) / 4

In [151]:
def categorize(data):
    if 0 < data <= 55:
        return "하"
    elif 55 < data <= 70:
        return "중"
    else:
        return "상"

In [152]:
df["평가분류"] = df["평균"].apply(categorize)

In [156]:
filter_df = df[df['평가분류'] == '상']
filter_df

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균 평가분류
2  C     62   89.0   72.4   66.0  72.35    상

In [155]:
filter_df_contains = df[df['평가분류'].str.contains('상', na=False)]
filter_df_contains

  코드  프로그램1  프로그램2  프로그램3  프로그램4     평균 평가분류
2  C     62   89.0   72.4   66.0  72.35    상

In [158]:
columns = ['코드', '평균', '평가분류']
selected_columns = filter_df_contains[columns]
selected_columns

  코드     평균 평가분류
2  C  72.35    상